### ISSUE TITLE
Any plans for DSL?

### ISSUE THREAD

**Issue by lolgear** [sersoft-gmbh/xmlwrangler#9]
Swift 5.1 announces Function builders ( as I remember they are delayed in 5.1, but it doesn't affect a question. ), it would be nice to have simple DSL to serialize XML :3

**Comment by ffried** [comment]
@lolgear This is definitively something we'd like to incorporate. However, given the many iterations that property wrappers (formerly known as property delegates) have gone through, we'll hold off function builders, until their implementation has reached a certain stability.

But once that has happened, I see little problems in integrating this functionality. Especially since XMLWrangler in it's current state does not have the variadic generics problem, that is one big part of the discussion [here](https://forums.swift.org/t/function-builders/25167).
